version: '3.5'
services:
  weak:
    image: nickadam/docker-weak-ssh:1.1
    volumes:
      - type: volume
        source: backup
        target: /backup
  daemon:
    image: nickadam/docker-cron-rsync:1.1
    build: .
    environment:
      CRON_SCHEDULE: '* * * * *'
      SOURCE: /data/
      DESTINATION: 'weak:/backup/'
      DOCKER_WEAK_SSH_HOST: weak
    volumes:
      - type: volume
        source: data
        target: /data
    depends_on:
      - weak
volumes:
  data:
  backup:
